// import { Component } from '@angular/core';

// @Component({
//   selector: 'app-profile',
//   templateUrl: './profile.component.html',
//   styleUrls: ['./profile.component.css'],
// })
// export class ProfileComponent {
//   newMessage: string = '';
//   chatMessages: string[] = [];
//   isEditing: boolean[] = [];
//   editedMessages: string[] = [];

//   sendMessage() {
//     if (this.newMessage.trim() !== '') {
//       this.chatMessages.push(this.newMessage);
//       this.newMessage = '';
//       this.isEditing.push(false);
//       this.editedMessages.push('');
//     }
//   }

//   startEditing(index: number) {
//     this.isEditing[index] = true;
//     this.editedMessages[index] = this.chatMessages[index];
//   }

//   saveEdit(index: number) {
//     if (this.editedMessages[index].trim() !== '') {
//       this.chatMessages[index] = this.editedMessages[index];
//       this.isEditing[index] = false;
//       this.editedMessages[index] = '';
//     }
//   }
// }

// import { Component } from '@angular/core';

// @Component({
//   selector: 'app-profile',
//   templateUrl: './profile.component.html',
//   styleUrls: ['./profile.component.css'],
// })
// export class ProfileComponent {
//   newMessage: string = '';
//   chatMessages: string[] = [];
//   isEditing: boolean[] = [];
//   editedMessages: string[] = [];

//   sendMessage() {
//     if (this.newMessage.trim() !== '') {
//       this.chatMessages.push(this.newMessage);
//       this.newMessage = '';
//       this.isEditing.push(false);
//       this.editedMessages.push('');
  
//       setTimeout(() => {
//         this.chatMessages.push(
//           "We're here to assist you in every step of your journey toward joining the institution. Let's start the process of helping you achieve your academic goals."
//         );
//         this.chatMessages.push("What’s your Full name?");
//       }, 1000);
//     }
//   }
  

//   startEditing(index: number) {
//     this.isEditing[index] = true;
//     this.editedMessages[index] = this.chatMessages[index];
//   }

//   saveEdit(index: number) {
//     if (this.editedMessages[index].trim() !== '') {
//       this.chatMessages[index] = this.editedMessages[index];
//       this.isEditing[index] = false;
//       this.editedMessages[index] = '';
//     }
//   }
// }

import { Component } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css'],
})
export class ProfileComponent {
  newMessage: string = '';
  chatMessages: string[] = [];
  isEditing: boolean[] = [];
  editedMessages: string[] = [];

  // Add a boolean variable to control the visibility of the chatbot content
  showAutoGeneratedMessages: boolean = false;

  // Add a boolean variable to control the visibility of the sendicon
  showSendIcon: boolean = false;

  // Function to generate and display auto-generated messages
  generateAutoMessages() {
    this.showAutoGeneratedMessages = true;
    // Also show the sendicon
    this.showSendIcon = true;
  }

  sendMessage() {
    if (this.newMessage.trim() !== '') {
      this.chatMessages.push(this.newMessage);
      this.newMessage = '';
      this.isEditing.push(false);
      this.editedMessages.push('');
    }
  }

  startEditing(index: number) {
    this.isEditing[index] = true;
    this.editedMessages[index] = this.chatMessages[index];
  }

  saveEdit(index: number) {
    if (this.editedMessages[index].trim() !== '') {
      this.chatMessages[index] = this.editedMessages[index];
      this.isEditing[index] = false;
      this.editedMessages[index] = '';
    }
  }
}


